- src/main/groovy/com/blackducksoftware/integration/hub/packman/packagemanager/ExecutableFinder.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/packman/packagemanager/PipPackageManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/packman/packagemanager/pip/PipPackager.java
- src/main/groovy/com/blackducksoftware/integration/hub/packman/util/Command.java
- src/main/resources/application.properties
Modified the way we search for executables and added Command object
> Started adding hub-pip support

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/HelpPrinter.groovy
@jrichardBD I had to adjust the padding to make the output look right. Could this perhaps be done dynamically? Or is it not worth the trouble?
> Added log level help

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/BomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/NugetBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/go/GoPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/gradle/GradleInitScriptPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/nuget/NugetInspectorPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipInspectorTreeParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/DetectFileService.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/FileHelper.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/SourcePathSearcher.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/executable/ExecutableManager.groovy
- src/main/resources/application.properties
- src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipInspectorTreeParserTest.groovy
A file service for helping with creating, writing, and cleanup of files.
Also serves as a wrapper for FileFinder.
> DetectFileService

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/NpmBomTool.groovy
I added a small amount of logging to help users understand when to run npm install if needed
> Npm bomtool update

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/DetectOption.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/HelpPrinter.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/ValueDescription.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/ValueDescriptionAnnotationFinder.groovy
Added the ability to sort help listing by the new group property for DetectProperties
> Help text group sorting

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
Added fields to more easily see what groups already exist and to add the same grouping consistently. An Enum may also be a good place to put these
> Properties grouping

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/type/BomToolType.java
Consider this as an alternative.
Also, I'm fairly certain we don't want to prevent bdio file creation in the normal case if this property is supplied.
> revising approach

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/MavenBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/nuget/NugetInspectorPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.groovy
We will now scan the tar file if it is provided and we will use, by default, the latest hub-docker-inspector.
> Adding docker scan

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/CondaBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/conda/CondaListElement.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/conda/CondaListParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/type/BomToolType.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/type/ExecutableType.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/executable/ExecutableRunner.groovy
- src/main/resources/application.properties
It produces bdio, but when uploaded to the hub I get no matches. I also tried using a '/' as the version separator. If anyone knows/can figure out how to get matches in the hub here let me know.
> Adding conda support

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/PipBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cpan/CpanListParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cpan/CpanPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cran/PackRatNodeParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cran/PackratPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/maven/MavenCodeLocationPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pear/PearDependencyFinder.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipInspectorTreeParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/rubygems/GemlockNodeParser.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/executable/ExecutableRunner.groovy
- src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipInspectorTreeParserTest.groovy
- src/test/groovy/com/blackducksoftware/integration/hub/detect/testutils/DependencyNodeUtil.groovy
I noticed @ekerwin used System.getProperty('line.separator') instead of '\n'. Replaced '\n' in a lot of places with Application.LINE_SEPARATOR
> Line separator

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/NpmBomTool.groovy
Fixed the issue with npm not running if there was an error and modified some logging. Also prevented NPM from running if yarn is applicable.
> Bomtool changes

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/maven/MavenCodeLocationPackager.groovy
- src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/maven/MavenCodeLocationPackagerTest.groovy
- src/test/resources/maven/sonarStashCodeLocation.json
- src/test/resources/maven/sonarStashCorruptCodeLocation.json
- src/test/resources/maven/sonarStashCorruptOutput.txt
- src/test/resources/maven/sonarStashOutput.txt
Increased maven parser leniency
> Maven parser improvements

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
Fixing issues with getting the shell script contents
> Fixing docker bom tool, certificate issues

- src/main/resources/hub-detect-sh
Added support for providing additional curl options for installations that need to go through a proxy or use self-signed certificates.
> added the ability to specify curl options when executing the shell script

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/gradle/GradleDependenciesParser.java
Trying to improve gradle's logic flow for sanity. I've tried not to modify any logic - hopefully I've succeeded.
> Refactoring gradle.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.groovy
We are now going to put all bdio output in one place and all scan output in another place.
> creating separate output directories for bdio and scan

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectInfo.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/TildeInPathResolver.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/executable/ExecutableManager.java
- src/test/groovy/com/blackducksoftware/integration/hub/detect/util/TildeInPathResolverTest.groovy
This allows us to "easily" convert the '~' character to the user's home directory.
> Support tilde

- build.gradle
- src/main/resources/application.properties
New timestamp with format that looks like
**2018-01-31 12:48:06 INFO---**
> Added to timestamp to logger

- src/main/groovy/com/blackducksoftware/integration/hub/detect/interactive/mode/DefaultInteractiveMode.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/interactive/mode/InteractiveMode.java
Adding warnings for the passwords in the interactive mode.
> Interactive mode warning

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/search/BomToolTreeSearcher.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/exception/BomToolException.java
> Tree walker revisions

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerProperties.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubServiceWrapper.java
Allow customers to ignore the proxy for certain hosts
> Adding ability to ignore proxy for the given host patterns

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/DetectOption.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/DetectOptionManager.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/FieldWarnings.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/print/DetectConfigurationPrinter.java
Attaching field warnings to detect options and moving away from printer so we can fail on them in the future.
> Field warnings and detect options.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/help/ArgumentStateParser.java
- src/test/groovy/com/blackducksoftware/integration/hub/detect/help/ArgumentStateParserTests.java
Fixing a help bug where it wasn't showing verbose or deprecated and it was not parsing value all the time.
> Fixing a parse and help bug. Adding help unit tests.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/yarn/YarnListParser.java
- src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/yarn/YarnListParserTest.groovy
Im updating the yarn list parsing to get the correct names from the yarn list when the name starts with an @ sign
> Correcting the yarn list parsing

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/go/godep/GoGodepsParser.groovy
- src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/go/GoGodepsParserTest.groovy
Updating the parsing due to https://github.com/blackducksoftware/hub-detect/issues/237
> Updating the go version parsing according to git describe

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubServiceWrapper.java
detect.disable.without.hub will, if set to true, make Detect to test Hub connectivity before it tries to run. If Detect does not connect to the Hub, it does nothing and exits quietly.
> Adding new property to succeed if hub connectivity is bad

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubManager.java
Adding the detect.project.description property to allow users to set the description of their created project.
> added the property detect.project.description

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CLangBomTool.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CLangExtractor.java
*
* IDETECT-725: fix "files for iScan" list
*
*
*
> IDETECT-725: fix "files for iScan" list

- README.md
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectOption.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/BeanConfiguration.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/conda/CondaCliExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cpan/CpanCliExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/cran/PackratLockBomTool.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pear/PearCliBomTool.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pear/PearCliExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pear/PearParseResult.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/rubygems/GemlockParser.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/util/executable/ExecutableRunner.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/DetectProjectManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/bomtool/BomToolEvaluation.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/extraction/Extraction.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/extraction/ExtractionReporter.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/extraction/ExtractionSummaryReporter.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/HubSignatureScanner.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/summary/DetectSummaryManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/summary/StatusSummaryProvider.java
A sonar-cloud prompted attempt to make the codebase of detect a bit healthier.
> Triage sonar issues

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/npm/NpmCliExtractor.java
*
* Arrays.asList is immutable and this will throw `java.lang.UnsupportedOperationException`
* Assign it with a different arraylist
*
*
> Fixes java.lang.UnsupportedOperationException

- build.gradle
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/hub/HubServiceWrapper.java
- hub-detect/hub-detect.gradle
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/BeanConfiguration.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/PolicyChecker.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/project/BdioManager.java
This should only be merged once hub-common 36.0.0 is released, but it gives a flavor of what is changing in hub-common for those who are interested.
> using latest hub-common

- build.gradle
- hub-detect/airgap.gradle
*
* Docker Inspector airgap fixes
*
*
*
> Sb fix air gap

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/DetectMajorVersion.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/ConfigurationManager.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectConfiguration.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectPropertyDeprecationOverrides.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectPropertySource.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectDeprecation.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectOptionManager.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/interactive/mode/DefaultInteractiveMode.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerProperties.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/BdioUploader.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/HubManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/HubSignatureScanner.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/OfflineScanner.java
Added new properties for them. New properties and old properties will automatically stay in sync. Added code to translate new properties into the expected format of hub common.
> Deprecating all hub related properties

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/npm/NpmCliExtractor.java
Added property for additional arguments to be passed when running the npm executable
> NPM Arguments

- build.gradle
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/hub/HubServiceManager.java
This will actually use the executor service during the scanning.
> Fix sig scanner offline

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/type/ExecutableType.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerBomTool.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/extraction/StandardExecutableFinder.java
> Sb use exe finder for java

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/util/DetectFileFinder.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/BlackDuckSignatureScanner.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/ExclusionPatternDetector.java
- hub-detect/src/test/groovy/com/blackducksoftware/integration/hub/detect/util/DetectFileFinderTest.java
Changes to, by default, limit the depth of the search for sig scanner exclusion patterns, which can take a very long time on big source dirs.
Things most worthy of scrutiny:
- The name of the new property
- default search depth (4)
- The changes to DetectFileFinder.findFilesRecursive()
> Sb limit scanner exclusion patterns search to given depth

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/lifecycle/boot/BootManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/lifecycle/boot/ConnectivityChecker.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/lifecycle/boot/ConnectivityResult.java
Trying to make it easier to follow.
> Improving connectivity check.

- build.gradle
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/ConnectionManager.java
- hub-detect/hub-detect.gradle
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/tool/polaris/PolarisTool.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/tool/signaturescanner/ScanBatchRunnerFactory.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/ArtifactResolver.java
Mild changes to support using the latest (not yet released) blackduck-common.
> using latest library
