blackducksoftware/hub-detect

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
So I chose to let Spring try to coerce the value first and we cleanup the output in DetectConfiguration instead of changing every field to a string and then coercing later. I felt it would be easier to read the DetectProperties file if the type was declared there.
> Changed DetectConfiguration to return primitives instead of nullable objects

- build.gradle
- src/main/resources/hub-detect-sh
Add the ability to explicitly override the version of Hub-Detect used.
The main use-case for this is if a new release breaks things for a customer, they can override to the previous version, turning a customer-down panic into a regular issue. In addition, this allows applications like CoPilot to test new releases within their workflow before rolling it out to customers.
The build.gradle generation was updated (and tested with a non-snapshot version number). The src/main/resources instance of the scrip was generated via this method as well.
Script has been used in a test project as generated both with and without overrides to verify continued working functionality
> Allow Override of Detect Version Used

- build.gradle
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/npm/NpmCliDependencyFinder.groovy
The gradle property was changed because the inspector relied on an older version of bdio, and I'm not a huge fan of having divergent dependencies.
The new version of hub-common has the latest integration-bdio library which fixed the builder, which allowed us to use it again in npm...which fixed everything.
> fixing npm

- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/util/DetectFileManager.groovy
The Docker Bom Tool is using the first file matching the pattern "*_dependencies.json" and it is not cleaning up after doing so. So it runs into an issue where it is using the *_dependencies.json from a previous run. It also seems to have the same issue with the tar file
> Fixing Docker bom tool issues

- airgap.gradle
- build.gradle
- src/main/groovy/com/blackducksoftware/integration/hub/detect/Application.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/NugetBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerInspectorManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/gradle/GradleInspectorManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/nuget/NugetInspectorManager.groovy
- src/main/resources/application.properties
The goal here is twofold- one, we want to create a build target for Detect that creates a single archive with all files needed to run Detect in an airgap environment. Two, we want customers to be able to execute in an airgap environment with as few flags as possible.
The airgap.gradle file contains all logic for constructing the archive, and is referenced by the build.gradle, so one can simply create an airgap archive by executing the createAirGapZip target.
The bomtools with inspectors now have unique logic for retrieving the version of the inspector that they use and will default to retrieving and utilizing the "latest" version, if available. If the versioning property is set to latest and the BomTool applies, it will attempt to resolve the actual version of the inspector that it is …
> Airgap refactor

- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.groovy
Example not scanning log:
` INFO--- Not scanning path C:\Users\jpiscitelli\Downloads\jackson-core-master\target, scan paths provided`
And detect results:
` INFO--- ======== Detect Results ========`
` INFO--- MAVEN : SUCCESS`
` INFO--- Scan Target C:\Users\jpiscitelli\Downloads\jackson-core-master\src : SUCCESS`
` INFO--- `
` INFO--- Overall Status : SUCCESS`
` INFO--- ================================`
> IDETECT-354: We don't register a scan if the detect.hub.signature.scanner.paths property has at least one path.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/test/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManagerTest.groovy
This makes slightly longer filenames in most cases (group, artifact, version) instead of (artifact, version) but should reduce conflicts. I've also improved the long filename ordering after talking with brian.
> New filename scheme based on external id instead of project name.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerProperties.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/BdioUploader.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/model/DetectProject.groovy
Now that detect can phone home with the meta data about which bom tools were applicable, docker doesn't need to run its own phone home anymore.
> Phone home bomtool data

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/packagist/PackagistParser.groovy
This is the least intrusive way I could find to do this. Minimum modifications.
> Adding Packagist discrepancy logs when composer.json and composer.lock mismatch

- src/main/resources/hub-detect-sh
Adding the the curl options to this call will allow for additional curl parameters to be set, including setting the proxy information. This pattern matches the rest of the curl calls in this file.
> added the curl options to a curl call that did not have them

- build.gradle
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectPhoneHomeManager.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/BdioUploader.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubServiceWrapper.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/model/BomToolType.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/model/DetectProject.groovy
Instead of introducing an explicit wait so that the phone home with all the meta data can complete, we now will simply phone home twice - once at the beginning of detect's run and a second time once we have all the data.
This is my attempt to remain true to the principle of not harming the customer with phone-home. Do these few seconds really matter? We can discuss.
> Phone home update

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectProjectManager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/DockerBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/GradleBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/MavenBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/NpmBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/SbtBomTool.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/nuget/NugetInspectorPackager.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.groovy
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/ScanPathSource.java
Now, each time a path is registered, the source of the register request is required (ScanPathSource). This can keep the logic of when to allow certain sources to register scan paths localized to the signature scanner code.
The big ideas are in HubSignatureScanner.
> creating the ScanPathSource

- src/main/resources/hub-detect-ps
In detect-ps: The uri is blank even after setting the host when the host contains a scheme. If I use "http://xyx.domainName.com" the Uri is blank but if I use "xyx.domainName.com" it works. 
This pull request uses UriBuilders constructor and let's it parse the host. This should prevent the uri from not being set when powershell script uses the proxy.
> Fixing a bug where having a scheme in the proxy host fails to parse.

- src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/nuget/NugetBomTool.groovy
This solves the issue of a single project being included in multiple solutions. For example, if I had one project Projects/ProjectA.csproj and it is referenced in SolutionA.sln and SolutionB.sln this will work.
It does not solve the problem of duplicate project names across all solutions. For example,  if I had two projects Projects/Web/ProjectA.csproj and Projects/Mobile/ProjectA.csproj and they are both referenced even in one solution SolutionA, this will still produce duplicate code location names.
> Nuget will combine 'solution project' code locations with same source path 

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
Customers are confused and concerned by our usage of the word "unknown" to describe a Detect version, so we should use a different phrase to properly communicate our message.
> Changing Detect Unknown Version to Default Detect Version

- src/main/groovy/com/blackducksoftware/integration/hub/detect/DetectConfiguration.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/codelocation/BomCodeLocationNameService.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/codelocation/CodeLocationNameService.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/codelocation/DockerCodeLocationNameService.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/codelocation/ScanCodeLocationNameService.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/hub/HubSignatureScanner.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/manager/CodeLocationNameManager.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/manager/DetectBdioManager.java
- src/main/groovy/com/blackducksoftware/integration/hub/detect/manager/DetectCodeLocationManager.java
- src/test/groovy/com/blackducksoftware/integration/hub/detect/CodeLocationNameFactoryTest.groovy
Adding a code location name manager (which is similar to the past code location name service unfortunately) and the code location factories are now services. The new manager handles incrementing previously given override names and choosing the correct factory for a code location name.
> Code location name override

- src/main/groovy/com/blackducksoftware/integration/hub/detect/extraction/bomtool/gradle/parse/GradleReportParser.java
The change to remove detect project from the bom tools was done incorrectly in the Gradle parser.
> Gradle project and version parsing fix.

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/BeanConfiguration.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/codelocation/CodeLocationNameManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/HubManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/project/BdioManager.java
Storing the code location names and waiting for those code locations explicitly when doing a policy check or report
> Updating to fix the Hub 4.7.0 delay

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/DependenciesListFileManager.java
* The clang extractor's running of the compiler had a side effect: It regenerated the .o (object) files. I don't know if this would ever be a real issue or not, but it certainly doesn't seem like the right thing to do. This change writes all compiler output to /dev/null instead.
*
*
*
*
> Clang: Compile source to /dev/null (instead of overwriting the .o file)

- hub-detect/src/main/resources/pip-inspector.py
**Why this pull request:**
* See https://jira.dc1.lan/browse/IDETECT-832
* pip v18 which was released Sunday, July 22, broke the hub-detect's pip-inspector.py and will cause hub-detect to fail - when run on python projects that use pip v18.
* This pull request proposes a (more future proof) fix for pip-inspector.py that works with pip 10, pip 18, and, assuming the pip team sticks with numerically ascending major version numbers going forward, should work for future versions as well. Assuming that the API endpoints we use in pip do not change also.
> fixing pip-inspector.py to work with pip v10+ (including v18)

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/DetectInfo.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/DetectMajorVersion.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectDeprecation.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectOption.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectOptionHelp.java
- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/help/DetectOptionManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/BeanConfiguration.java
This should fix our deprecation cycle. We will not fail based on warnings. We deprecate in a major version. We fail in a major version. We remove in a major version.
> Changing deprecation cycle and attribute fields.

- hub-detect/src/main/resources/hub-detect-sh
When the rm fails we just keep appending. This fix will overwrite the file even if the rm fails.
> Updating shell script to overwrite existing file

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/ClangExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CompileCommand.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CompileCommandWrapper.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/DependenciesListFileManager.java
- hub-detect/src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/ClangExtractorTest.java
- hub-detect/src/test/resources/clang/source/build/compile_commands_usesArguments.json
*
* Previously we expected the command field to be present in compile_commands.json. Turns out, either commands or arguments is required; commands is not required. So I added the arguments field to the data object, and a wrapper class that will provide whichever is present when asked for it.
*
*
*
> Sb clang support json arguments or command441

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/pip/PipInspectorBomTool.java
Questions about these changes: What do you think of:
1. The wording of the new messages.
2. The point at which the "pip inspector is deprecated" message is logged
> deprecate pip inspector and the detect.pip.requirements.path property

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/ClangExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/ClangLinuxPackageManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CompileCommand.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CompileCommandJsonData.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/CompileCommandsJsonFile.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/DependenciesListFileManager.java
- hub-detect/src/test/groovy/com/blackducksoftware/integration/hub/detect/bomtool/clang/ClangExtractorTest.java
Clang: Fixed the cast exception (concurrency) problem by synchronizing on the (multi-threaded) set operations
> Sb multithread clang extr safely

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/BeanConfiguration.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/docker/DockerInspectorManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/gradle/GradleInspectorExtractor.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/bomtool/gradle/GradleInspectorManager.java
- hub-detect/src/main/resources/init-script-gradle.ftl
Now detect (not gradle) downloads the gradle inspector jar, and it by default gets it from the new bds artifactory url
> Sb move gradle inspector to artifactory

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/DetectConfigurationFactory.java
Greetings,
The function call will not have its intended effect because the positions of arguments in the constructor for DetectToolFilter do not match the ordering of the parameters:
* excludedTools is passed to includedTools
* includedTools is passed to excludedTools
Signed-off-by: Bryon Gloden, CISSP® <cissp@bryongloden.com>
> Fix DetectConfigurationFactory.java

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/util/DetectZipUtil.java
The unsanitized path of a zip archive entry, which may contain '..', was used
directly to resolve the destination path for the files being unzipped.
Extracting files from a malicious archive without validating that the
destination file path is within the destination directory can cause files
outside the destination directory to be overwritten.
* N/A
* This PR fixes an instance of ZipSlip that was [detected on LGTM.com](https://lgtm.com/projects/g/blackducksoftware/hub-detect/alerts/?mode=tree&tag=&ruleFocus=1506728586782)
*  Verify that the normalized full path of the output file starts with a prefix that matches the destination directory …
> Fix ZipSlip bug found by LGTM.com

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/detector/go/GopkgLockParser.java
Greetings,
The . character in the pattern "golang.org/x/" can match any character because calls to **replaceAll** treat the pattern as a regular expression, which might be unexpected. That is to say, a string intended to be matched literally is instead treated as a regular expression, changing its meaning. To replace all occurrences of the literal string, use **replace** instead of **replaceAll**.
Signed-off-by: Bryon Gloden, CISSP® cissp@bryongloden.com
> Fix GopkgLockParser.java

- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/HubManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/PolicyChecker.java
There are some other ways to accomplish this. We could do a pre-check on the existence of the policy-status link. Not sure what you'd like to do.
> fixing when policy status is not present

- detect-configuration/src/main/java/com/blackducksoftware/integration/hub/detect/configuration/DetectProperty.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/configuration/DetectConfigurationFactory.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/lifecycle/run/RunManager.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/DetectProjectMappingService.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/DetectProjectMappingView.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/DetectProjectService.java
- hub-detect/src/main/groovy/com/blackducksoftware/integration/hub/detect/workflow/hub/DetectProjectServiceOptions.java
N/A
Customer's would like to set a project's Application ID when running Detect
Added a DetectProjectMappingService which aids in the getting/setting/and deletion of project-mappings
> Added ability for users to set the project's 'Application ID' setting via a property
